use crate::devices::volca_drum::volca_drum_patch::{
    VolcaDrumPatch, VolcaDrumPatchLayout, VolcaDrumPatchLayoutAmpEg, VolcaDrumPatchLayoutModType,
    VolcaDrumPatchLayoutSoundSrcType,
};

pub fn get_volca_drum_patch_1() -> VolcaDrumPatch {
    VolcaDrumPatch {
        kick: VolcaDrumPatchLayout {
            sound_src_type: VolcaDrumPatchLayoutSoundSrcType::WaveSine,
            mod_type: VolcaDrumPatchLayoutModType::ModExp,
            amp_eg: VolcaDrumPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 80,
            eg_attack: 5,
            eg_release: 50,
            mod_amount: 120,
            mod_rate: 120,
        },
        hh: VolcaDrumPatchLayout {
            sound_src_type: VolcaDrumPatchLayoutSoundSrcType::WaveSine,
            mod_type: VolcaDrumPatchLayoutModType::ModExp,
            amp_eg: VolcaDrumPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
        snare: VolcaDrumPatchLayout {
            sound_src_type: VolcaDrumPatchLayoutSoundSrcType::WaveSaw,
            mod_type: VolcaDrumPatchLayoutModType::ModExp,
            amp_eg: VolcaDrumPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 40,
            eg_attack: 5,
            eg_release: 50,
            mod_amount: 120,
            mod_rate: 120,
        },
        sound4: VolcaDrumPatchLayout {
            sound_src_type: VolcaDrumPatchLayoutSoundSrcType::WaveSine,
            mod_type: VolcaDrumPatchLayoutModType::ModExp,
            amp_eg: VolcaDrumPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
        sound5: VolcaDrumPatchLayout {
            sound_src_type: VolcaDrumPatchLayoutSoundSrcType::WaveSine,
            mod_type: VolcaDrumPatchLayoutModType::ModExp,
            amp_eg: VolcaDrumPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
        sound6: VolcaDrumPatchLayout {
            sound_src_type: VolcaDrumPatchLayoutSoundSrcType::WaveSine,
            mod_type: VolcaDrumPatchLayoutModType::ModExp,
            amp_eg: VolcaDrumPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
    }
}
