use crate::song::yaml_patch_reader::{
    YamlPatchFile, YamlPatchLayout, YamlPatchLayoutAmpEg, YamlPatchLayoutModulationType,
    YamlPatchLayoutSoundSrcType,
};

pub fn get_volca_drum_patch_1() -> YamlPatchFile {
    YamlPatchFile {
        kick: YamlPatchLayout {
            sound_src_type: YamlPatchLayoutSoundSrcType::WaveSine,
            mod_type: YamlPatchLayoutModulationType::ModExp,
            amp_eg: YamlPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 80,
            eg_attack: 5,
            eg_release: 50,
            mod_amount: 120,
            mod_rate: 120,
        },
        hh: YamlPatchLayout {
            sound_src_type: YamlPatchLayoutSoundSrcType::WaveSine,
            mod_type: YamlPatchLayoutModulationType::ModExp,
            amp_eg: YamlPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
        snare: YamlPatchLayout {
            sound_src_type: YamlPatchLayoutSoundSrcType::WaveSaw,
            mod_type: YamlPatchLayoutModulationType::ModExp,
            amp_eg: YamlPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 40,
            eg_attack: 5,
            eg_release: 50,
            mod_amount: 120,
            mod_rate: 120,
        },
        sound4: YamlPatchLayout {
            sound_src_type: YamlPatchLayoutSoundSrcType::WaveSine,
            mod_type: YamlPatchLayoutModulationType::ModExp,
            amp_eg: YamlPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
        sound5: YamlPatchLayout {
            sound_src_type: YamlPatchLayoutSoundSrcType::WaveSine,
            mod_type: YamlPatchLayoutModulationType::ModExp,
            amp_eg: YamlPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
        sound6: YamlPatchLayout {
            sound_src_type: YamlPatchLayoutSoundSrcType::WaveSine,
            mod_type: YamlPatchLayoutModulationType::ModExp,
            amp_eg: YamlPatchLayoutAmpEg::EnvAd,
            level: 127,
            pitch: 37,
            eg_attack: 13,
            eg_release: 9,
            mod_amount: 9,
            mod_rate: 20,
        },
    }
}
